apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: auto1
targetKind: pod
minReplicas: 1
maxReplicas: 5
metrics:
  resource:
    - name: cpu
      min: 20%
      max: 50%
    - name: memory
      min: 1MB
      max: 128MB
label:
  app: auto2
  env: product
spec:
  containers:
    - name: busy1
      image: 7143192/auto1:latest # an endless loop function image.
      command:
      args:
      workingDir: /
      volumeMounts:
        - name: v1
          mountPath: /volume

      ports:
        - name: d
          containerPort: 99
          # hostPort: 10099
          protocol: TCP

      # memory format: xxxKB / xxxMB / xxxGB
      # mini limit for memory is 4MB.
      resources:
        limits:
          cpu: 100m
          memory: 64MB
        requests:
          cpu: 100m
          memory: 64MB

    - name: busy2
      image: nginx:latest # an endless loop function image.
      command:
      args:
      workingDir: /
      volumeMounts:
        - name: v1
          mountPath: /volume

      ports:
        - name: d
          containerPort: 99
          # hostPort: 10099
          protocol: TCP

      # memory format: xxxKB / xxxMB / xxxGB
      # mini limit for memory is 4MB.
      resources:
        limits:
          cpu: 100m
          memory: 64MB
        requests:
          cpu: 100m
          memory: 64MB

  volumes:
    - name: v1
      hostPath: /home/volume2
