apiVersion: v1
kind: Node
metadata:
  # character "/" is not allowed in the metadata.Name !!!
  # but character "_", "-" should be allowed.
  name: node2
  label: node2
  port: 9001
  ip: 192.168.1.7
  selector:
    gpu: nvidia