apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: test4
    env: product
nodeSelector:
  gpu: nvidia
spec:
  containers:
    - name: p4c1
      image: busybox:latest
      command:
      args:
      workingDir: /
      volumeMounts:
        - name: pod4_vol
          mountPath: /volume
      ports:
        - name: port1
          containerPort: 90
          # hostPort: 10090
          protocol: TCP
      # memory format: xxxKB / xxxMB / xxxGB
      # mini limit for memory is 4MB.
      resources:
        limits:
          cpu: 1.60
          memory: 5GB
        requests:
          cpu: 1.60
          memory: 5GB
  volumes:
    - name: pod4_vol
      hostPath: /home/working3
