apiVersion: v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rsTest
        env: product
    spec:
      containers:
        - name: aaa
          image: busybox:latest
          command:
          args:
          workingDir: /
          volumeMounts:
            - name: v0
              mountPath: /volume
          ports:
            - name: d
              containerPort: 90
              # hostPort: 10090
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 64MB
            requests:
              cpu: 100m
              memory: 64MB
        - name: bbb
          image: busybox:latest
          command:
          args:
          workingDir: /
          volumeMounts:
            - name: v0
              mountPath: /volume
          ports:
            - name: d
              containerPort: 100
              # hostPort: 7070
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 64MB
            requests:
              cpu: 100m
              memory: 64MB
      volumes:
        - name: v0
          hostPath: /home/volume1