apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: ClusterIP
  clusterIP: 10.0.0.1
  ports:
    - port: 11000
      targetPort: 11000
      protocol: TCP
  selector:
    app: ""
    env: product
