apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  type: ClusterIP
  clusterIP: 10.0.0.3
  ports:
    - port: 11002
      targetPort: 11002
      protocol: TCP
  selector:
    app: test1
    env: product