apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: ClusterIP
  clusterIP: 10.0.0.2
  ports:
    - port: 11001
      targetPort: 11001
      protocol: TCP
  selector:
    app: test1
    env: ""