# shrink
apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: auto1
targetKind: pod
minReplicas: 2
maxReplicas: 5
metrics:
  resource:
    - name: cpu
      min: 30%
      max: 50%
    - name: memory
      min: 100MB
      max: 1GB
label:
  app: auto1
  env: product
spec:
  containers:
    - name: con1
      image: busybox:latest
      command:
      args:
      workingDir: /home/os/Desktop/working
      volumeMounts:
        - name: cc
          mountPath: ccc

      ports:
        - name: d
          containerPort: 99
          # hostPort: 10099
          protocol: TCP

      # memory format: xxxKB / xxxMB / xxxGB
      # mini limit for memory is 4MB.
      resources:
        limits:
          cpu: 100m
          memory: 64MB
        requests:
          cpu: 100m
          memory: 64MB

    - name: con2
      image: busybox:latest
      command:
      args:
      workingDir: /home/os/Desktop/working1
      volumeMounts:
        - name: cc
          mountPath: ccc

      ports:
        - name: d
          containerPort: 77
          # hostPort: 7777
          protocol: TCP

      # memory format: xxxKB / xxxMB / xxxGB
      # mini limit for memory is 4MB.
      resources:
        limits:
          cpu: 100m
          memory: 64MB
        requests:
          cpu: 100m
          memory: 64MB

  volumes:
    - name: v0
      hostPath: /home/os/Desktop/volume1
