apiVersion: v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
      env: default
  template:
    metadata:
      name: deployPod1
      labels:
        app: app1
        env: default
    spec:
      containers:
        - name: con1
          image: busybox:latest
          command:
          args:
          workingDir: /home/os/Desktop/working
          volumeMounts:
            - name: cc
              mountPath: ccc

          ports:
            - name: d
              containerPort: 90
              # hostPort: 11090
              protocol: TCP

          # memory format: xxxKB / xxxMB / xxxGB
          # mini limit for memory is 4MB.
          resources:
            limits:
              cpu: 100m
              memory: 64MB
            requests:
              cpu: 100m
              memory: 64MB

      volumes:
        - name: v2
          hostPath: /home/os/Desktop/volume1
