apiVersion: v1
kind: Pod
metadata:
  name: s
  labels:
    app: test1
    env: product
nodeSelector:
  gpu: nvidia
spec:
  containers:
    - name: aaa
      image: 7143192/pod_basic:latest
      command: ["/bin/bash", "-c", "/home/testserver"]
      args:
      workingDir: /
      volumeMounts:
        - name: v0
          mountPath: /volume
      ports:
        - name: d
          containerPort: 90
          # hostPort: 10090
          protocol: TCP
      # memory format: xxxKB / xxxMB / xxxGB
      # mini limit for memory is 4MB.
      resources:
        limits:
          cpu: 100m
          memory: 64MB
        requests:
          cpu: 100m
          memory: 64MB
    - name: bbb
      image: busybox:latest
      command:
      args:
      workingDir: /
      volumeMounts:
        - name: v0
          mountPath: /volume
      ports:
        - name: d
          containerPort: 100
          # hostPort: 7070
          protocol: TCP
      # memory format: xxxKB / xxxMB / xxxGB
      # mini limit for memory is 4MB.
      resources:
        limits:
          cpu: 100m
          memory: 64MB
        requests:
          cpu: 100m
          memory: 64MB
  volumes:
    - name: v0
      hostPath: /home/os/Desktop/working
