apiVersion: v1
kind: Pod
metadata:
  name: ssss
  labels:
    app: test4
    env: product
nodeSelector:
  gpu: nvidia
spec:
  containers:
    - name: aaa
      image: busybox:latest
      command:
      args:
      workingDir: /home/os/Desktop/working
      volumeMounts:
        - name: v1
          mountPath: /home/os/Desktop/working
      ports:
        - name: d
          containerPort: 90
          # hostPort: 10090
          protocol: TCP
      # memory format: xxxKB / xxxMB / xxxGB
      # mini limit for memory is 4MB.
      resources:
        limits:
          cpu: 1.60
          memory: 5GB
        requests:
          cpu: 1.60
          memory: 5GB
  volumes:
    - name: v0
      hostPath: /home/os/Desktop/working
