apiVersion: v1
kind: ReplicaSet
metadata:
  name: rs-example2
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: bar
        env: default
    spec:
      containers:
        - name: aaa
          image: busybox:latest
          command:
          args:
          workingDir: /home/os/Desktop/working
          volumeMounts:
            - name: cc
              mountPath: ccc
          ports:
            - name: d
              containerPort: 90
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 64MB
            requests:
              cpu: 100m
              memory: 64MB
        - name: bbb
          image: busybox:latest
          command:
          args:
          workingDir: /home/os/Desktop/working1
          volumeMounts:
            - name: cc
              mountPath: ccc
          ports:
            - name: d
              containerPort: 100
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 64MB
            requests:
              cpu: 100m
              memory: 64MB
      volumes:
        - name: v0
          hostPath: /home/os/Desktop/volume1