apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: NodePort
  clusterIP: 10.0.0.2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8080
      protocol: TCP
  selector:
    app: test1
    env: product
